/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-30 05:48:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1679993008539L));
    _jspx_dependants.put("jar:file:/C:/selfWork/yosangso/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/881d1deef7.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 슬라이더 파일다운받은거 -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <title>index</title>\r\n");
      out.write("    \r\n");
      out.write("    <!--탑 버튼 & 스크립트 html 부분-->\r\n");
      out.write("    \r\n");
      out.write("    <!--탑 버튼-->\r\n");
      out.write("    <a id=\"topBtn\" href=\"#\"> \r\n");
      out.write("        <i class=\"fa-solid fa-angles-up fa-2x\"></i>\r\n");
      out.write("    </a> \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 헤더, 컨텐츠 -->\r\n");
      out.write("    <main>\r\n");
      out.write("    \r\n");
      out.write("    	<!-- 헤더 -->\r\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <!-- 내용 작성 공간입니다.(template2) -->\r\n");
      out.write("        <!-- content 전체 감싸는 영역 -->\r\n");
      out.write("        <section class=\"content-container\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 왼쪽사이드 -->\r\n");
      out.write("            <section class=\"leftSide\">\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 가운데페이지 -->\r\n");
      out.write("            <section class=\"center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 1. 메인페이지 슬라이더 사진 영역 -->\r\n");
      out.write("                <section class=\"mainViewPhoto\">\r\n");
      out.write("                                 \r\n");
      out.write("                    <div id=\"visual\">\r\n");
      out.write("                        <div class=\"on\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/메인슬라이더1편집.jpg\"  width=\"100%\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/메인슬라이더2편집.jpg\" width=\"100%\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/메인슬라이더3편집.png\" width=\"100%\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 2 베스트부분 시작 -->\r\n");
      out.write("                <section class=\"bestPart\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- 2-1 베스트 글씨 -->\r\n");
      out.write("                    <div class=\"mainFont bestFont\">베스트</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 2-2 베스트 제품 -->\r\n");
      out.write("                    <div class=\"bestItem\"> \r\n");
      out.write("\r\n");
      out.write("                        <!-- 베스트제품1 -->\r\n");
      out.write("                        <div class=\"BNitem Bitem1\">    \r\n");
      out.write("                            <a href=\"#\">    \r\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\"> \r\n");
      out.write("                                    <figcaption>베스트제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto1\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\r\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \r\n");
      out.write("                                </div> \r\n");
      out.write("                            \r\n");
      out.write("                                <div class=\"BNitemPrice bestItem1Price\">75,000원</div>  \r\n");
      out.write("                        </div>                        \r\n");
      out.write("\r\n");
      out.write("                                                 \r\n");
      out.write("                        <!-- 베스트제품2 -->  \r\n");
      out.write("                        <div class=\"BNitem Bitem2\">  \r\n");
      out.write("                            <a href=\"#\">  \r\n");
      out.write("                                <div class=\"BNitemPic bestItem2Pic\"> \r\n");
      out.write("                                    <figcaption>베스트제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption> \r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                        alt=\"제품사진\" id=\"bestItemPhoto2\"> \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <div class=\"BNitemName bestItem2Name\">\r\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                </div> \r\n");
      out.write("                            \r\n");
      out.write("                                <div class=\"BNitemPrice bestItem2Price\">75,000원</div>\r\n");
      out.write("                        </div>                       \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 베스트제품3 -->\r\n");
      out.write("                        <div class=\"BNitem Bitem3\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"BNitemPic bestItem3Pic\">\r\n");
      out.write("                                    <figcaption>베스트제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto3\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"BNitemName bestItem3Name\">\r\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>  \r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"BNitemPrice bestItem3Price\">75,000원</div>  \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 베스트제품4 -->\r\n");
      out.write("                        <div class=\"BNitem Bitem4\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"BNitemPic bestItem1Pic\">\r\n");
      out.write("                                    <figcaption>베스트제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                    alt=\"제품사진\" id=\"bestItemPhoto4\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"BNitemName bestItem1Name\">\r\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분) </a>\r\n");
      out.write("                                </div>        \r\n");
      out.write("\r\n");
      out.write("                                <div class=\"BNitemPrice bestItem4Price\">75,000원</div>\r\n");
      out.write("                        </div> \r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 2-3 베스트제품더보기 -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"more bestMore\">\r\n");
      out.write("                            <a href=\"#\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 3 신제품부분 시작 -->\r\n");
      out.write("                <section class=\"newPart\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- 3-1 신제품 글씨 -->\r\n");
      out.write("                    <div class=\"mainFont newFont\">신제품</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 3-2 신제품 순 -->\r\n");
      out.write("                    <div class=\"newItem\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- 신제품1 -->\r\n");
      out.write("                        <div class=\"BNitem Nitem1\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"BNitemPic newItem1Pic\">\r\n");
      out.write("                                    <figcaption>신제품1<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto1\">  \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <div class=\"BNitemName newItem1Name\">\r\n");
      out.write("                                    <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a> \r\n");
      out.write("                                </div>\r\n");
      out.write("                           \r\n");
      out.write("                                <div class=\"BNitemPrice newItem1Price\">65,000원</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 신제품2 -->\r\n");
      out.write("                        <div class=\"BNitem Nitem2\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"BNitemPic newItem2Pic\">\r\n");
      out.write("                                    <figcaption>신제품2<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto2\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <div class=\"BNitemName newItem2Name\">\r\n");
      out.write("                                    <a href=\"#\">신제품2 설명</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            \r\n");
      out.write("                                <div class=\"BNitemPrice newItem2Price\">신제품2 가격</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 신제품3 -->\r\n");
      out.write("                        <div class=\"BNitem Nitem3\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"BNitemPic newItem3Pic\">\r\n");
      out.write("                                    <figcaption>신제품3<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto3\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <div class=\"BNitemName newItem3Name\">\r\n");
      out.write("                                    <a href=\"#\">신제품3 설명</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"BNitemPrice newItem3Price\">신제품3 가격</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 신제품4 -->\r\n");
      out.write("                        <div class=\"BNitem Nitem4\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"BNitemPic newItem4Pic\">\r\n");
      out.write("                                    <figcaption>신제품4<br><br> 상세설명칸<br><br> 입니다 </figcaption>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                        alt=\"제품사진\" id=\"newItemPhoto4\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                                <div class=\"BNitemName newItem4Name\">\r\n");
      out.write("                                    <a href=\"#\">신제품4 설명</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              \r\n");
      out.write("                                <div class=\"BNitemPrice newItem4Price\">신제품4 가격</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 3-3 신제품 더보기 -->\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"more newMore\">\r\n");
      out.write("                            <a href=\"#\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 신제품부분 끝  -->\r\n");
      out.write("                </section>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <!-- 4 제품부분 시작 -->\r\n");
      out.write("                <section class=\"itemPart\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- 4-1 제품글씨 -->\r\n");
      out.write("                    <div class=\"mainFont itemFont\">제품</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 4-2 제품모음 -->\r\n");
      out.write("                    <div class=\"itemGather\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 제품 1 ~3 -->\r\n");
      out.write("                        <div class=\"itemFirst\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품1 -->\r\n");
      out.write("                            <div class=\"item item1\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item1Pic\">\r\n");
      out.write("                                        <figcaption>제품1<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto1\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                \r\n");
      out.write("                                    <div class=\"itemName item1Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item1Price\">16,000원</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품2 -->\r\n");
      out.write("                            <div class=\"item item2\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item2Pic\">\r\n");
      out.write("                                        <figcaption>제품2<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto2\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>    \r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item2Name\">\r\n");
      out.write("                                        <a href=\"\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item2Price\">16,000원</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품3 -->\r\n");
      out.write("                            <div class=\"item item3\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item3Pic\">\r\n");
      out.write("                                        <figcaption>제품3<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto3\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                               \r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item3Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item3Price\">16,000원</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 제품 4~6 -->\r\n");
      out.write("                        <div class=\"itemSecond\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품4 -->\r\n");
      out.write("                            <div class=\"item item4\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item4Pic\">\r\n");
      out.write("                                        <figcaption>제품4<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto4\"> \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item4Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item4Price\">16,000원</div>    \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품5 -->\r\n");
      out.write("                            <div class=\"item item5\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item5Pic\">\r\n");
      out.write("                                        <figcaption>제품5<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\"  \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto5\">   \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item5Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item5Price\">16,000원</div>  \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품6 -->\r\n");
      out.write("                            <div class=\"item item6\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item6Pic\">\r\n");
      out.write("                                        <figcaption>제품6<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\"  \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto6\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item6Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item6Price\">16,000원</div> \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- 제품7~9 -->\r\n");
      out.write("                        <div class=\"itemThird\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품7 -->\r\n");
      out.write("                            <div class=\"item item7\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item7Pic\">\r\n");
      out.write("                                        <figcaption>제품7<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\"  \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto7\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                \r\n");
      out.write("                                    <div class=\"itemName item7Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item7Price\">16,000원</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품8 -->\r\n");
      out.write("                            <div class=\"item item8\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item8Pic\">\r\n");
      out.write("                                        <figcaption>제품8<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto8\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item8Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item8Price\">16,000원</div> \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- 제품9 -->\r\n");
      out.write("                            <div class=\"item item9\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <div class=\"itemPic item9Pic\">\r\n");
      out.write("                                        <figcaption>제품8<br><br>상세설명칸<br><br>입니다</figcaption>\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/제품_오쏘뮬.jpg\" \r\n");
      out.write("                                            alt=\"이미지입니다\" id=\"itemPhoto9\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemName item9Name\">\r\n");
      out.write("                                        <a href=\"#\">[오쏘뮬] 오쏘뮬 이뮨 멀티비타민&미네랄 14입+1입 증정 기획 (2주분)</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"itemPrice item9Price\">16,000원</div> \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                    <!-- 4-3 제품더보기 더보기 -->\r\n");
      out.write("                    <div class=\"itemMore\"> \r\n");
      out.write("                        <a href=\"#\">더보기 <i class=\"fa-solid fa-angles-right\" id=\"allow\"> </i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- 제품부분 끝 -->\r\n");
      out.write("                </section>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 가운데페이지 끝 -->\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 오른쪽사이드바 -->\r\n");
      out.write("            <section class=\"rightSide\">\r\n");
      out.write("\r\n");
      out.write("                 <!-- 인체사진 플로팅바-->\r\n");
      out.write("                 <div class=\"floating\">\r\n");
      out.write("                    <a href=\"#\"> \r\n");
      out.write("                        <img id=\"people\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/index/인체이미지누끼.png\" >\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"cart/shoppingCart\" method=\"get\">\r\n");
      out.write("				<input type=\"text\" name=\"userNum\">\r\n");
      out.write("				<button>담기</button>\r\n");
      out.write("			</form>\r\n");
      out.write("            <form action=\"refund\" method=\"get\">\r\n");
      out.write("				<input type=\"text\" name=\"memberNo\">\r\n");
      out.write("				<button>환불페이지 부르기</button>\r\n");
      out.write("			</form>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- content 전체 감싸는 영역 끝 -->\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    <!-- 헤더, 컨텐츠 끝 -->\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 -->\r\n");
      out.write("  	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- jQuery 라이브러리 추가 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   \r\n");
      out.write("    <!-- main.js 연결 -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
